const base = {
  black: '#000',
  cherry: '#CC4B3E',
  cherry_dark: '#B33225',
  cherry_light: '#EC786C',
  cherry_lighter: '#F8EFEE',
  concrete: '#565A5C',
  concrete_light: '#ECECEC',
  concrete_lighter: '#FAFAFA',
  concrete_medium: '#AFB0B2',
  cyan: '#008A83',
  cyan_dark: '#005F5B',
  cyan_light: '#54BBBA',
  cyan_lighter: '#E8F3F3',
  mikado: '#FBB80E',
  mikado_dark: '#E29F00',
  mikado_light: '#FCC947',
  mikado_lighter: '#FFF6E2',
  overlay: 'rgba(0, 0, 0, 0.3)',
  white: '#FFF',
};

const colors = {
  background: base.white,
  background_dark: base.black,
  border: base.concrete_light,
  border_hover: base.concrete,
  connect: base.cyan_light,
  disabled_background: base.concrete_light,
  foreground_primary: base.white,
  foreground_quaternary: base.concrete,
  foreground_secondary: base.concrete_lighter,
  foreground_tertiary: base.cyan_lighter,
  instant_booking: base.mikado_light,
  label_primary: base.concrete,
  label_quaternary: base.white,
  label_secondary: base.concrete_medium,
  label_tertiary: base.cyan,
  negative: base.cherry,
  negative_background: base.cherry_lighter,
  negative_hover: base.cherry_dark,
  overlay: base.overlay,
  placeholder: base.concrete_medium,
  positive: base.cyan,
  positive_background: base.cyan_lighter,
  positive_hover: base.cyan_dark,
  separator: base.concrete_light,
};

export default colors;
